# Generated by Django 5.2 on 2025-05-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buslocation",
            name="speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
