# Generated by Django 5.2 on 2025-05-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_buslocation_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="last_known_location_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="last_maintenance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="maintenance_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("in_maintenance", "In Maintenance"),
                    ("out_of_commission", "Out of Commission"),
                    ("delayed", "Delayed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="next_maintenance_due",
            field=models.DateField(blank=True, null=True),
        ),
    ]
