# Generated by Django 5.2 on 2025-05-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_school_buslocation_heading_route_stops_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buslocation",
            name="is_trip_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="buslocation",
            name="is_trip_start",
            field=models.BooleanField(default=False),
        ),
    ]
