# Generated by Django 5.2 on 2025-05-10 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_buslocation_is_trip_end_buslocation_is_trip_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buslocation",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
