# Generated by Django 5.2 on 2025-05-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_buslocation_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="last_known_heading",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="last_known_speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
