"""
Django settings for bus_management project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib import messages

# SESSION_COOKIE_SECURE = True

# CSRF_COOKIE_SECURE = True

# SECURE_HSTS_SECONDS = 31536000

# SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_HSTS_PRELOAD = True

# SECURE_SSL_REDIRECT = True

# SECURE_REFERRER_POLICY = 'strict-origin'

# SECURE_BROWSER_XSS_FILTER = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-sa+&_ktk&rf*to=$hd71c+p0+dw4oh6=r)an6!l*7fq#sva*5d"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sites",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_extensions',
    'rest_framework',
    'import_export',
    'django_filters',
    'drf_yasg',
    'core',
]

SITE_ID = 1

# Custom user model
AUTH_USER_MODEL = 'core.CustomUser'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bus_management.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "bus_management.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql_psycopg2",
#         "NAME": os.getenv("DB_NAME", ""),
#         "USER": os.getenv("DB_USER", ""),
#         "PASSWORD": os.getenv("DB_PASSWORD", ""),
#         "HOST": os.getenv("DB_HOST", ""),
#         "PORT": os.getenv("DB_PORT", ""),
#     }
# }

# Mapbox settings
MAPBOX_ACCESS_TOKEN = os.getenv('MAPBOX_ACCESS_TOKEN')

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Add this to your REST_FRAMEWORK settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        },
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'LOGIN_URL': 'admin:login',
    'LOGOUT_URL': 'admin:logout',
    'USE_SESSION_AUTH': True,
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Asia/Dubai'

USE_I18N = True

USE_TZ = True

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Collect static files here in production
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Project-level static files directory
]

# Media files (User-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # Store user-uploaded files here

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Jazzmin Settings (Deep Personalization)
JAZZMIN_SETTINGS = {
    "site_title": "School Bus Monitor",
    "site_header": "Modern International School",
    "site_brand": "Bus Monitoring",
    "site_icon": "/static/img/bus_logo.png",  # Ensure you have a logo here
    "welcome_sign": "Welcome to the School Bus Monitoring System",
    "copyright": "Modern International School",
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],  # Dynamically controlled by permissions in admin.py
    "hide_models": [],  # Dynamically controlled by permissions in admin.py
    "order_with_respect_to": ["accounts", "buses", "routes", "students", "tracking", "communication"],

    # Custom CSS for extra flair
    "custom_css": "/css/admin_custom.css",

    # Custom JS if needed
    "custom_js": None,

    # Use Google Fonts CDN for better typography
    "use_google_fonts_cdn": True,

    # Form format settings
    "changeform_format": "horizontal_tabs",  # Use tabs for forms
    "changeform_format_overrides": {"auth.user": "vertical_tabs"},

    # Theme customization - Choose a vibrant theme
    "show_ui_tweaks": True,
    "theme": "flatly",  # A vibrant, professional theme (explore others like 'cosmo', 'lumen', 'simplex')

    # Adding a custom dashboard view
    "index_title": "Dashboard",  # Set the admin index title
    "main_url": "/",  # Link to the custom dashboard view (overridden in urls.py)

    # Enhanced color palette for cards/elements
    "colors": {
        "primary": "#0d6efd",  # Vibrant blue for primary actions
        "secondary": "#6c757d",  # Neutral gray for secondary actions
        "success": "#198754",  # Green for success messages
        "danger": "#dc3545",  # Red for errors or warnings
        "warning": "#ffc107",  # Yellow for warnings
        "info": "#0dcaf0",  # Teal for informational messages
        "light": "#f8f9fa",  # Light background
        "dark": "#212529",  # Dark text or borders

        # Custom branding colors
        "brand_blue": "#0d6efd",  # Brand-specific blue
        "brand_green": "#198754",  # Brand-specific green
        "brand_orange": "#fd7e14",  # Brand-specific orange
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,

    # Navbar styling
    "brand_colour": "navbar-light",  # Match navbar color to theme
    "layout_boxed": False,  # Full-width layout
    "layout_fixed_sidebar": True,  # Fixed sidebar for better navigation
    "layout_fixed_navbar": True,  # Fixed navbar at the top
    "layout_fixed_footer": False,  # Footer is not fixed

    # Sidebar styling
    "sidebar_non_expandable_links": False,  # Allow sidebar links to expand
    "sidebar_boxed": False,  # Full-width sidebar
    "sidebar_collapse": False,  # Do not collapse the sidebar by default
    "sidebar_nav_small_text": False,  # Normal-sized text in the sidebar
    "sidebar_nav_child_indent": True,  # Indent child items for better hierarchy
    "sidebar_nav_compact_style": False,  # Standard spacing for sidebar items
    "sidebar_nav_legacy_style": False,  # Modern sidebar style
    "sidebar_nav_flat_style": False,  # Rounded corners for sidebar items

    # Theme settings
    "theme": "flatly",  # Ensure this matches JAZZMIN_SETTINGS['theme']

    # Button classes
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },

    # Input and select styles
    "input_classes": "form-control",
    "select_classes": "form-select",

    # Modal styles
    "modal_classes": {
        "modal-dialog": "modal-dialog-centered",  # Center modals vertically
        "modal-content": "modal-content",
        "modal-header": "modal-header",
        "modal-body": "modal-body",
        "modal-footer": "modal-footer"
    },

    # Card styles
    "card_classes": "card",  # Use Bootstrap card class
    "card_outline": "card-outline-primary",  # Example card outline color
    "card_styling": "card-primary",  # Example card background color (can be overridden in templates)
}

# Django Redis Cache Settings
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1", # Update with your Redis server details
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Email Settings (Configure for sending emails)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # Use console for testing
# Configure for production:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'your_email_host'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_email_user'
# EMAIL_HOST_PASSWORD = 'your_email_password'
# DEFAULT_FROM_EMAIL = 'from@example.com'

# SMS Settings (Placeholder - Integrate with a service like Twilio)
SMS_GATEWAY_API_KEY = 'your_sms_api_key' # CHANGE THIS!
SMS_GATEWAY_API_SECRET = 'your_sms_api_secret' # CHANGE THIS!
SMS_FROM_NUMBER = 'your_sms_from_number' # CHANGE THIS!

# Geopy User Agent (Required for Nominatim)
GEOPY_USER_AGENT = 'school_bus_monitor'

# Import-Export Settings (Optional, for permission control)
# IMPORT_EXPORT_IMPORT_PERMISSION_CODE = 'import' # Example custom permission
# IMPORT_EXPORT_EXPORT_PERMISSION_CODE = 'export' # Example custom permission